### PR TITLE
fix  Pair tag   getStyle()   execution failure 

### PR DESCRIPTION
**Pull request by QingMings**
fix  Pair tag   getStyle()   execution failure  ，see issus #77

### CODE REVIEW

**Comment by balhar-jakub** [comment]
The changes to the Style resolver seems fine to me and all changes associated to this: KmlStyleMap, Pair, StyleResolver. 
What I don't understand is why the change in the jszip.js What is the reason behind this change. The rest seems ok for the merge, but I need to understand this one. Could you provide some example of file, which works incorrectly without this change?

**Comment by QingMings** [comment]
In   `KmlFile.js`  ，
The 83 line.

83  `         kmzFile.files.forEach(function (file) {   `
 84`                          if (file.endsWith(".kml") && rootDocument == null) {`
  85`                             if (file.name.endsWith(".kml") && rootDocument == null) {`
 86   `                              rootDocument = file.asText();`
   87`                          }`
    88 `                   });`

The  `kmlFile.files`  is  a object  ,not a  array , can‘t use   `forEach` method .
 So i change the `jszip.js`   ，  let it return a Array .
Maybe I'm not doing it right. Just to solve the problem, without considering the rationality.
Sorry for this .

**Comment by balhar-jakub** [comment]
I missed this one. Don't change the jszip. Instead this code should be changed. It should be working if it is changed to:

    Object.keys(kmzFile.files).forEach(function(key){
        var file = kmzFile.files[key];
    });

Retrieve all the relevant files and then manage the previous function on each of them. Is it obvious what I am trying to explain?

**Comment by QingMings** [comment]
Maybe you can help me with this  #84 ，

**Comment by QingMings** [comment]
yes, I understand，I will correct it。:)

**Pull request closed without merging**
