### PR TITLE
Corrected outdated comment and file capitalization

### LINKED ISSUE #303: Deep Picking example filename capitalization error
### Description

The DeepPicking example html file has a capital I in the filename after the P in picking. 

### Operating System and Version

Ubuntu 16.04/Chrome 61

### LINKED ISSUE #326: Deep Picking example references wrong line in comments
### Description

The comments note to look at line 117; however, it is now line 116

### Steps to Reproduce

1. Open file

**Expected behavior:** [What you expect to happen]

Note line 116 instead of 117

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### PR DESCRIPTION
**Pull request by Beak-man**
### Description of the Change
- Corrected mistaken capitalization in DeepPicking.html filename. (It was "DeepPIcking.html").
- Corrected outdated line reference in comment.

### Applicable Issues
Closes #303
Closes #326 

Substitutes PR #397

### CODE REVIEW

**Comment by zglueck** [comment]
Instead of referencing the line number in the comment, what if the relevant line and pick handling function were brought to the top of the example? The explicit line reference would then be removed as the relevant parts of the example would reside at the top of the file.

**Comment by Beak-man** [comment]
@zglueck I think it's a good idea and It'll ease maintenance. I just made the appropriate changes. Do you think its readability is improved?

**Comment by pdavidc** [comment]
@Beak-man why have most lines in this example changed? There doesn't seem to be any difference.

**Comment by markpet49** [comment]
@pdavidc I wondered that too. The change is that the lines moved higher in the file per @zglueck suggestions.

**Comment by markpet49** [comment]
Other than that, it looks OK to me and it ran fine.

**Comment by Beak-man** [comment]
Yeah, the highlighting code was moved to the beginning as per @zglueck 's suggestion, but the logic didn't change.

**Pull request merged**
