### PR TITLE
Feature/build suggestions

### LINKED ISSUE #143: Review and continue work on branch feature/build_suggestions
The aforementioned branch implements many steps that streamline the build process. This will be useful for purposes of publishing the artifacts to npm and other CI-related tasks.

### PR DESCRIPTION
**Pull request by Beak-man**
This is the summary of the changes:

- Include @AkeluX changes to streamline artifact building.
- Removed zip file compress task from build process.
- Removed `grunt-contrib-compress` node module from package.json, since it became an unused dependency because of the previous point.
- Updated markdown build guide to reflect the new streamlined build process
- Added package-lock.json file generated by npm. It is suggested to commit it into the repository. See: https://docs.npmjs.com/files/package-lock.json
- package.json had spaces in "type" and "url" declarations that were automatically removed in build process.
- Added .idea/ folder to .gitignore. Consider removing the folder from the repository altogether.

Issue #146 is related but still pending, since we'll prioritize npm deployment based on this branch.

Closes #143

### CODE REVIEW

**Comment by Beak-man** [comment]
@pdavidc Thanks for the feedback.

1. OK, we won't be removing .idea/ from the repository then. I saw that my IDE configuration was modified in the merge, and didn't want to change the configuration for everyone else. Should I remove the folder from .gitignore, though? Every git status I do tells me I'm changing something in there, and thus far I have avoided to commit any staged changes my IDE setup produces in there.

2. @AkeluX made build.js unnecessary by adding the `grunt` command at the scripts section of package.json. But build.js was used before this. I did add it again in the merge just to be sure that I understood why it was gone only to remove it afterwards.

3. I didn't move test-main.js, but I'll review why it was done. What do you think @AkeluX?

**Comment by pdavidc** [comment]
Regarding #1: The .idea folder contains a mix of files we want to share and files we want on the Git ignore list. Take a look at Android's .gitignore and model Web's based on that, adjusting for the Web project as necessary:
https://github.com/NASAWorldWind/WorldWindAndroid/blob/develop/.gitignore

**Comment by Beak-man** [comment]
Thanks a lot for the clarification. Now I understand that runConfigurations is meant to be there. I modified .gitignore so it's an analogue of the one in Android.

**Comment by pdavidc** [comment]
Thanks for taking care of that. Since you're already changing .gitignore, I noticed that the following are missing:

- .idea/shelf
- node_modules
- test-results
- standalone-data

The .idea/shelf folder is created by WebStorm when you use the Shelve Changes feature, and is associated with the local environment. The others were previously in the .gitignore, and it's unclear to me why they've been removed. Finally, let's use the line spacing convention found in Android. Now that we're modifying the file I see no reason to be inconsistent.

**Comment by pdavidc** [comment]
@Beak-man My apologies for the confusion, I see now that node_modules, test-results and standalone-data are still in .gitignore. I simply needed to expand the diff.

In addition to the other still-relevant points in my previous post, how about removing the reference to WebWorldWind.zip?

**Comment by Beak-man** [comment]
Right! I had forgotten about the zip file. The line spacing is now added, as well as the reference to .idea/shelf

**Pull request merged**
