### PR TITLE
It is possible now to load kmz files.

### PR DESCRIPTION
**Pull request by balhar-jakub**
Fixing incorrect handling of files retrieved from JSZip

### CODE REVIEW

**Comment by pdavidc** [comment]
@balhar-jakub Thanks for making this fix.

@AkeluX Have you reviewed these changes?

**Comment by AkeluX** [comment]
@pdavidc no, I haven't. Will do.

**Comment by AkeluX** [comment]
@balhar-jakub could you check my changes? Let me know if you have any questions.

**Comment by AkeluX** [comment]
Today, we've confirmed that the latest changes are fine.

**Pull request merged**
