### PR TITLE
Improve the GeoJSON example

### PR DESCRIPTION
**Pull request by claudiaifrim**
### Description of the Change
Fix bugs in geojson example and update geojson files used as showcases.

### Why Should This Be In Core?
Improve usability and fix data inconsistencies for geojson example.

### Benefits
Improve usability and fix data inconsistencies for geojson example.

### Potential Drawbacks
None detected.

### CODE REVIEW

**Comment by claudiaifrim** [comment]
@AkeluX, the new files used in this example are available in examples/data/geojson-data/ folder and must be uploaded at https://worldwind.arc.nasa.gov/web/examples/data/geojson-data/

**Comment by pdavidc** [comment]
@AkeluX @claudiaifrim I've updated the GeoJSON example data online.

**Comment by pdavidc** [comment]
@AkeluX @claudiaifrim Does this pull request close issue #304?

**Comment by claudiaifrim** [comment]
@pdavidc yep!

**Comment by pdavidc** [comment]
Thanks @claudiaifrim !

**Pull request merged**
