### PR TITLE
Add meta tag for charset in all examples

### LINKED ISSUE #364: Example HTML character encoding
When I open the Annotations.html example I receive this error in the console:

The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.

Tested on Linux Mint 18.2 Cinnamon, Firefox 57.0.

### LINKED ISSUE #760: Firefox: The character encoding of the HTML document was not declared
### Description

If you open any example in Firefox you will receive this error in the console:

"The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol."

### Steps to Reproduce

1. Open any example in Firefox browser.

**Reproduces how often:** 100%

### Operating System and Version

Linux Mint 18.2, Firefox 58.0

### Additional Information

To fix this the meta tag above should be inserted in head of html example files.

< meta charset="utf-8" / >

### PR DESCRIPTION
**Pull request by claudiaifrim**
### Description of the Change
Add meta tag for charset in all html files - examples and apps.

### Why Should This Be In Core?
Fixes a bug for Firefox.

### Benefits
Fixes a bug for Firefox.

### Potential Drawbacks
None.

### Applicable Issues
Closes #364 
Closes #760

### CODE REVIEW

**Comment by eirizarry** [comment]
@pdavidc, @AkeluX 

Tested in Chrome and Firefox (from Annotations to ParseURLArguments), and tested all examples in Safari. 

There is no error for meta-tag, but Simplest Example is not working in all browsers, and GeographicText is not loading in Chrome--here's a screenshot of the errors in the browser console for this example. 

screen shot 2018-07-24 at 2 16 37 pm

**Comment by pdavidc** [comment]
@eirizarry If you run the problematic examples multiple times, do they reliably produce this error?

**Comment by eirizarry** [comment]
GeographicText example works fine now, but SimplestExample is still not working in all browsers.

**Comment by pdavidc** [comment]
SimplestExample doesn't work when run locally.

**Pull request merged**
