### PR TITLE
Enhanced the accuracy of ElevationModel's min/max elevations

### PR DESCRIPTION
**Pull request by pdavidc**
ElevationModel's min/max elevations interface is used indirectly by terrain and image tile rendering to determine level of detail. This change restores min/max accuracy to its pre-composition state, ensuring that terrain and image level of detail behaves as it has been.

- Corrected minElevation and maxElevation to return zero when the model has no coverages, or when all coverages are disabled
- Updated minAndMaxElevationsForSector to consult only the necessary coverages for a given sector
- Updated ElevationModel's unit tests to account for changes in the minAndMaxElevationsForSector interface and behavior
- Relates to epic #575

### CODE REVIEW

**Comment by pdavidc** [comment]
I agree. However, indicating whether or not the min/max indicates whether the sector is filled is the whole intent of this change. Can you think of an alternate approach that might function just as well, while producing the intended result?

**Comment by zglueck** [comment]
I'm missing nuances here which I'm sure are important, so I apologize ahead of time for dumb questions/suggestions!

Would it be better as two separate methods? e.g.
```
if (coverage.hasCompleteDataForSectpr(sector)) {
    coverage.minAndMaxElevationsForSector(sector, result)
}
```

**Comment by pdavidc** [comment]
Yes, that would be a more concise design. However, it would incur the overhead of assembling and checking the coverage tiles for that sector twice. That's a fairly expensive operation.

I think the real problem here is that the elevation model system has taken on responsibilities that really don't belong to it. In this case, the elevation system is partially responsible for constructing terrain and image tile bounding boxes via minAndMaxElevationsForSector. If you look closely at how this method operates, you'll see behavioral that terrain and imagery depend on, but which don't really make sense for the elevation model. I have it in mind to address coupling between elevations and terrain/image tiles with a new epic.

In the meantime, we need an approach that's conceptually good enough, but performs well.

**Comment by zglueck** [comment]
That sounds like the best solution! No additional comments from my end 👍

**Pull request merged**
