### PR TITLE
Fix for picking transparent placemarks

### PR DESCRIPTION
**Pull request by markpet49**
### Description of the Change
Shader fix for picking placemarks and other textures that are mostly transparent. Includes a test case in the PlacemarksAndPicking example.

### CODE REVIEW

**Comment by PJHogan** [comment]
Wahoo!

**Comment by PJHogan** [comment]
If Unblocked!!!

**Comment by PJHogan** [comment]
Ooch! Ouch!

**Review by Beak-man — APPROVED** [review]
Looks good!

**Pull request merged**
